# Generated by Django 4.1.1 on 2022-10-17 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("practice", "0003_user"),
    ]

    operations = [
        migrations.DeleteModel(
            name="User",
        ),
    ]
