# Generated by Django 4.1.1 on 2022-10-18 18:09

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ("practice", "0004_delete_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="image",
            field=imagekit.models.fields.ProcessedImageField(
                blank=True, upload_to="images/"
            ),
        ),
    ]
