# Generated by Django 4.1.1 on 2022-10-22 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("practice", "0007_article_like_users_comment_parent_comment"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="like_count",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
